# Estágio de build
FROM maven:3.9.6-amazoncorretto-21-debian as build

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo pom.xml
COPY ./pom.xml .

# Copie o código-fonte do projeto
COPY ./src ./src

# Execute o comando Maven para construir o JAR, ignorando testes
RUN mvn clean package -e -DskipTests

# Estágio de runtime
FROM eclipse-temurin:17-jre-alpine

# Defina o diretório de trabalho
WORKDIR /app

# Copie o JAR gerado do estágio de build
COPY --from=build /app/target/*.jar app.jar

# Comando para executar o JAR
CMD ["java", "-jar", "app.jar"]
