name: Auto PR from Developer Branch

on:
  push:
    branches:
      - teste-aws

permissions:
  contents: write
  pull-requests: write

jobs:
  open_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automated Pull Request'
          body: |
            This pull request is automatically created from the Developer branch.
          base: main  # A branch para a qual a PR será aberta
          head: teste-aws  # A branch de origem